package com.identity.Constain;

public enum PermissionNameEnum {
    NAME_CUSTOMER_CREATE,
    NAME_CUSTOMER_WRITE,
    NAME_CUSTOMER_READ,
    NAME_LOAN_CREATE,
    NAME_LOAN_WRITE,
    NAME_LOAN_SUBMIT,
    NAME_CREDIT_CHECK,
    NAME_LOAN_READ_ALL,
    NAME_LOAN_APPROVE,
    NAME_LOAN_REJECT,
    NAME_REPORT_VIEW,
    NAME_DISBURSEMENT_EXECUTE,
    NAME_REPAYMENT_COLLECT,
    NAME_FINANCIAL_REPORT,
    NAME_USER_CREATE,
    NAME_USER_WRITE,
    NAME_USER_READ,
    NAME_SYSTEM_CONFIG,
    NAME_AUDIT_LOG_VIEW
}

